/* Auto-generated by wav2c.py — do not edit */
#ifndef EMBEDDED_SAMPLES_H
#define EMBEDDED_SAMPLES_H

typedef struct {
    const char *name;
    const unsigned char *data;
    unsigned int size;
} sq_embedded_sample_t;

extern const sq_embedded_sample_t SQ_EMBEDDED_SAMPLES[];
extern const int SQ_NUM_EMBEDDED_SAMPLES;

#endif /* EMBEDDED_SAMPLES_H */
