#!/usr/bin/env python3
"""Convert WAV files to a C source file with embedded byte arrays."""

import os

# Resolve paths relative to the project root (parent of tools/)
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SAMPLES = [
    ("samples/808/01.BD.808.wav",  "sample_bd_808",  "808 Kick"),
    ("samples/808/01.SD5.808.wav", "sample_sd5_808", "808 Snare"),
    ("samples/808/01.CH.808.wav",  "sample_ch_808",  "808 HiHat"),
    ("samples/808/01.CP.808.wav",  "sample_cp_808",  "808 Clap"),
    ("samples/808/01.OH.808.wav",  "sample_oh_808",  "808 OpenHH"),
    ("samples/808/01.CB.808.wav",  "sample_cb_808",  "808 Cowbell"),
    ("samples/808/01.RS.808.wav",  "sample_rs_808",  "808 Rimshot"),
    ("samples/808/01.HT.808.wav",  "sample_ht_808",  "808 HiTom"),
]

OUT_C = os.path.join(PROJECT_ROOT, "src/plugin/embedded_samples.c")
OUT_H = os.path.join(PROJECT_ROOT, "src/plugin/embedded_samples.h")

def wav_to_c_array(filepath, varname):
    with open(filepath, "rb") as f:
        data = f.read()
    size = len(data)
    lines = []
    lines.append(f"/* {os.path.basename(filepath)} — {size} bytes */")
    lines.append(f"static const unsigned char {varname}[] = {{")
    # Format 16 bytes per line
    for i in range(0, size, 16):
        chunk = data[i:i+16]
        hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
        comma = "," if i + 16 < size else ""
        lines.append(f"    {hex_vals}{comma}")
    lines.append("};")
    return "\n".join(lines), size

def main():
    # Generate .c file
    c_parts = []
    c_parts.append("/* Auto-generated by wav2c.py — do not edit */")
    c_parts.append('#include "embedded_samples.h"')
    c_parts.append("")

    sizes = []
    for relpath, varname, _name in SAMPLES:
        filepath = os.path.join(PROJECT_ROOT, relpath)
        array_str, size = wav_to_c_array(filepath, varname)
        c_parts.append(array_str)
        c_parts.append("")
        sizes.append(size)
        print(f"  {varname}: {size} bytes")

    # Lookup table
    c_parts.append("const sq_embedded_sample_t SQ_EMBEDDED_SAMPLES[] = {")
    for (_filepath, varname, name) in SAMPLES:
        c_parts.append(f'    {{"{name}",{" " * (12 - len(name))}{varname},{" " * (16 - len(varname))}sizeof({varname})}},')
    c_parts.append("};")
    c_parts.append(f"const int SQ_NUM_EMBEDDED_SAMPLES = {len(SAMPLES)};")
    c_parts.append("")

    with open(OUT_C, "w") as f:
        f.write("\n".join(c_parts))
    print(f"Wrote {OUT_C} ({sum(sizes)} total sample bytes)")

    # Generate .h file
    h_lines = []
    h_lines.append("/* Auto-generated by wav2c.py — do not edit */")
    h_lines.append("#ifndef EMBEDDED_SAMPLES_H")
    h_lines.append("#define EMBEDDED_SAMPLES_H")
    h_lines.append("")
    h_lines.append("typedef struct {")
    h_lines.append("    const char *name;")
    h_lines.append("    const unsigned char *data;")
    h_lines.append("    unsigned int size;")
    h_lines.append("} sq_embedded_sample_t;")
    h_lines.append("")
    h_lines.append("extern const sq_embedded_sample_t SQ_EMBEDDED_SAMPLES[];")
    h_lines.append("extern const int SQ_NUM_EMBEDDED_SAMPLES;")
    h_lines.append("")
    h_lines.append("#endif /* EMBEDDED_SAMPLES_H */")
    h_lines.append("")

    with open(OUT_H, "w") as f:
        f.write("\n".join(h_lines))
    print(f"Wrote {OUT_H}")

if __name__ == "__main__":
    main()
